version: '3'

services:

  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    image: wp-graphql/wordpress:${WP_VERSION:-latest}
    build:
      context: ./docker
      args:
        PHP_VERSION: ${PHP_VERSION:-8.0}
    depends_on:
      - mysql
      - mysql_phpunit
    ports:
      - "8080:80"
    volumes:
      - ./local/public:/var/www/html # WP core files.
      - .:/var/www/html/wp-content/plugins/wp-graphql-testcase
      - ./local/config/wp-config.php:/var/www/html/wp-config.php
      - ./local/config/wp-tests-config.php:/var/www/html/wp-tests-config.php
      - ./local/config/.htaccess:/var/www/html/.htaccess
      - ./local/config/enable-app-passwords.php:/var/www/html/wp-content/mu-plugins/enable-app-passwords.php
    env_file: .env.testing
    environment:
      APACHE_RUN_USER: "#1000" # Ensure Apache can write to the filesystem.
      WP_TESTS_DIR: /var/www/html/wp-content/plugins/wp-graphql-testcase/vendor/wp-phpunit/wp-phpunit
      WP_PHPUNIT__TESTS_CONFIG: /var/www/html/wp-tests-config.php

  mysql_phpunit:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""